version: 2
jobs:
  test:
    docker:
      - image: circleci/python3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up bats
          command: |
            git clone https://github.com/sstephenson/bats.git ~/bats
            cd ~/bats
            sudo ./install.sh /usr/local
      - run:
          name: unit tests
          command: |
            cd starts-with-verb
            pip install -r requirements.txt
            pip install -r dev_requirements.txt
            make test
      - run:
          name: integration test
          command: |
            cd starts-with-verb
            make remote-integration-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
